<?php

/**
 * @file
 * Contains programacion.module.
 */


function programacion_page_attachments(array &$attachments)
{
    $attachments['#attached']['library'][] = 'programacion/programacion-testjs-library';
}

/**
 * Implements hook_theme().
 */
function programacion_theme($existing, $type, $theme, $path)
{
    return [
        'test1' => [
            'variables' => ['test_var' => NULL],
        ],
    ];
}